# All the rules accept the following parameters: opt, threads, mem

# Configuration file version (do not change)
config_version: 8

# MAIN RULES
get_genome:
    opt: ""

get_annotation:
    opt: ""

pbt_fastq_filter:
    opt: "--remove_duplicates --min_len 100 --min_qual 7"

minimap2_index:
    opt: ""

minimap2_align:
    opt: "-x map-ont -L"
    threads: 4

pbt_alignment_filter:
    opt: "--min_align_len 100 --min_freq_identity 0.7 --skip_unmapped --skip_secondary --skip_supplementary"

# OPTIONAL DNA METHYLATION RULES, Comment to skip
pbt_alignment_split:
    opt: ""
    n_chunks: 10

nanopolish_index:
    opt: ""

nanopolish_call_methylation:
    opt: "--methylation cpg"
    threads: 4

# OPTIONAL PYCOMETH RULES, Comment to skip
pycometh_cgi_finder:
    opt: ""

pycometh_cpg_aggregate:
    opt: "--min_depth 5 --min_llr 2"

pycometh_interval_aggregate:
    opt: "--min_cpg_per_interval 5 --min_llr 2"

pycometh_meth_comp:
    opt: "--max_missing 1 --min_diff_llr 2 --pvalue_threshold 0.01"

pycometh_comp_report:
    opt: "--max_tss_distance 100000 --pvalue_threshold 0.01 --min_diff_llr 1"

# OPTIONAL STRUCTURAL VARIANT RULES, Comment to skip
ngmlr:
    opt: "-x ont"
    threads: 4

sniffles:
    opt: "--min_support 5 --max_num_splits 7 --max_distance 1000 --min_length 30 --minmapping_qual 10"

# OPTIONAL QC RULES, Comment to skip
pycoqc:
    opt: "--filter_calibration --filter_duplicated --min_pass_len 100 --min_pass_qual 7"

samtools_qc:
    opt: ""

# OPTIONAL COVERAGE RULES, Comment to skip
bedtools_genomecov:
    opt: "-bg"

igvtools_count:
    opt: "-w 10"
