{% set version = '0.1a2' %}
{% set name = "pycoSnake" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: "pip install {{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -v "
  entry_points:
    - pycoSnake=pycoSnake.__main__:main
  noarch: "python"

requirements:
  build:
    - python>=3.6
    - pip>=19.2.1
    - ripgrep=11.0.1
  run:
    - python>=3.6
    - snakemake=5.5.4
    - pandas=0.24.1
    - loguru=0.3.2
    - ftputil=3.4

test:
  commands:
    - pycoSnake --help
    - pycoSnake RNA_illumina --help
    - pycoSnake DNA_ONT --help
    - pycoSnake test_wrappers --help

about:
  home: "https://github.com/a-slide/pycoSnake"
  license: "MIT"
  summary: "pycoSnake is a neatly wrapped collection of snakemake workflows for analysing nanopore sequencing data"
