{% set version = "0.2.5" %}
{% set name = "pycoSnake" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: "pip install {{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -vv "
  entry_points:
    - pycoSnake=pycoSnake.__main__:main
  noarch: "python"

requirements:
  build:
    - python>=3.6
  run:
    - python>=3.6
    - snakemake-minimal
    - pandas
    - ftputil

test:
  commands:
    - pycoSnake --help
    - pycoSnake RNA_illumina --help
    - pycoSnake DNA_ONT --help
    - pycoSnake test_wrappers --help

about:
  home: https://github.com/a-slide/pycoSnake
  license: MIT
  summary: pycoSnake is a neatly wrapped collection of snakemake workflows for analysing Illumina and nanopore sequencing datasets. It is easy to install with conda and simple to run on a local computer or in a cluster environment

extra:
  author: Adrien Leger
  author_email: aleg@ebi.ac.uk
  author_url: https://adrienleger.com
