{% set version = '0.0.3.7' %}
{% set name = "NanoSnake" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: "pip install {{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -v "
  entry_points:
    - NanoSnake=NanoSnake.__main__:main
  noarch: "python"

requirements:
  build:
    - python>=3.6
    - pip>=19.2.1
    - ripgrep=11.0.1
  run:
    - python>=3.6
    - snakemake=5.5.4
    - pandas=0.24.1
    - loguru=0.3.2
    - ftputil=3.4

test:
  commands:
    - NanoSnake --help
    - NanoSnake RNA_illumina --help
    - NanoSnake DNA_ONT --help
    - NanoSnake test_wrappers --help

about:
  home: "https://github.com/a-slide/NanoSnake"
  license: "MIT"
  summary: "NanoSnake is a neatly wrapped collection of snakemake workflows for analysing nanopore sequencing data"
