{% set version = "__package_version__" %}
{% set name = "__package_name__" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: "pip install {{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -vv "
  entry_points:
    - __entry_point1__
  noarch: "python"

requirements:
  build:
    - python__minimal_python__
  run:
    - python__minimal_python__
    - __dependency_1_conda__
    - __dependency_2__
    - __dependency_3__

test:
  commands:
    - pycoSnake --help
    - pycoSnake RNA_illumina --help
    - pycoSnake DNA_ONT --help
    - pycoSnake test_wrappers --help

about:
  home: __package_url__
  license: __package_licence__
  summary: __package_description__

extra:
  author: __author_name__
  author_email: __author_email__
  author_url: __author_url__
