 Configuration file version (do not change)
config_version: 7

# Source files
# Path to an ENSEMBL FASTA reference genome file/URL to be used for read mapping (local, FTP or HTTP)
genome:
# Path to an ENSEMBL GFF3 annotation file/URL containing transcript annotations (local, FTP or HTTP)
annotation:
# Path to an ENSEMBL cDNA FASTA reference transcriptome file/URL to be used for read counting (local, FTP or HTTP)
transcriptome:
# Path to a tabulated sample sheet
sample_sheet:

# Conditional execution of pipeline
cufflinks: True
featurecounts: True
salmon: True
quality_control: True
genome_coverage: True

# All the rules accept the following parameters: opt, threads, mem

get_genome:
    opt: ""

get_transcriptome:
    opt: ""

get_annotation:
    opt: ""

fastp:
    opt: ""
    threads: 2

star_index:
    opt: ""
    threads: 4

star_align:
    opt: "--outFilterType BySJout  --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000"
    threads: 4

pbt_alignment_filter:
    opt: "--min_align_len 50 --min_freq_identity 0.7 --skip_unmapped --skip_secondary --skip_supplementary"
    threads: 1

star_count_merge:
    opt: ""

cufflinks:
    opt: "--library-type fr-firststrand --upper-quartile-norm"
    threads: 4

cufflinks_fpkm_merge:
    opt: ""

subread_featurecounts:
    opt: "-p"
    threads: 2

subread_featurecounts_merge:
    opt: ""

samtools_qc:
    opt: ""

bedtools_genomecov:
    opt: "-bg"

igvtools_count:
    opt: "-w 10"

salmon_index:
    opt: ""
    threads: 4

salmon_quant:
    opt: "--libType A --validateMappings"
    threads: 4

salmon_count_merge:
    opt: ""
